project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1- Geospatial Data Wrangling"
            href: "/Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"  
          - text: "Hands-on Exercise 1 - Part 2- Choropleth Mapping"  
            href: "/Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html"  
          - text: "Hands-on Exercise 2 - Part 1- 1st Order Spatial Point Patterns Analysis"  
            href: "/Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html"
          - text: "Hands-on Exercise 2 - Part 2- 2nd Order Spatial Point Patterns Analysis"  
            href: "/Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html"
          - text: "Hands On Exercise 3- Network Constrained Spatial Point Patterns Analysis"  
            href: "/Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands On Exercise 4- Spatial Weights and Applications"  
            href: "/Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
          - text: "Hands On Exercise 5- Global Spatial Autocorrelation"  
            href: "/Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html"
          - text: "Hands On Exercise 5- Part 2- Local Measures of Spatial Autocorrelation"  
            href: "/Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html"
          - text: "Hands On Exercise 6- Geographical Segmentation with Spatially Constrained Clustering Techniques"  
            href: "/Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
      - text: "Take-Home Exercise"
        menu: 
          - text: "Take Home Exercise 1"
            href: "/Take-home_Ex/Take-home_Ex1/Take-home_Ex01.html"
          - text: "Take Home Exercise 2"
            href: "/Take-home_Ex/Take-home_Ex2/Take-home_Ex02.html"
      - text: "In Class Exercise"
        menu: 
          - text: "In Class Exercise 1"
            href: "/In-class_Ex/In-class_Ex1/In-class_Ex1.html"
          - text: "In Class Exercise 2"
            href: "/In-class_Ex/In-class_Ex2/In-class_Ex2.html"
          - text: "In Class Exercise 3"
            href: "/In-class_Ex/In-class_Ex3/In-class_Ex3.html"
          - text: "In Class Exercise 4"
            href: "/In-class_Ex/In-class_Ex4/In-class_Ex4.html"
          - text: "In Class Exercise 5"
            href: "/In-class_Ex/In-class_Ex5/In-class_Ex5.html"
          - text: "In Class Exercise 6"
            href: "/In-class_Ex/In-class_Ex6/In-class_Ex6.html"
    right: 
      - text: Home
        href: "/index.html"
        

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual



